#!/bin/bash

raspivid -n -t 0 -h 200 -w 320 -fps 25 -hf -b 2000000 -o - | gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=1 pt=96 ! gdppay ! tcpserversink host=192.168.1.11 port=5000

#raspivid -t 0 -hf -n -h 480 -w 640 -fps 15 -o - | nc -l -p 5001
